@startuml
title Use case dijagram
left to right direction

actor "Roditelj" as Roditelj
actor "Administrator\n(predškolska ustanova)" as Admin
actor "Zdravstvo servis\n(mock API)" as ZdrSrv <<System>>

rectangle "Servis predškolske ustanove" as Predskolsko {
  usecase "Pregled svoje dece" as UC_MojaDeca
  usecase "Podnošenje zahteva\nza upis" as UC_Podnesi
  usecase "Odobravanje zahteva" as UC_Odobri
  usecase "Odbijanje zahteva" as UC_Odbij
  usecase "Raspoređivanje deteta\nu grupu" as UC_Grupa
  usecase "Evidencija dolaska/\npreuzimanja" as UC_Evidencija
  usecase "Pregled evidencije\nprisustva" as UC_PregledPrisustva
}

rectangle "Servis zdravstvo (mock)" as Zdravstvo {
  usecase "Provera zdravstvene\nknjižice" as UC_Knjizica
  usecase "Provera obaveznog\npregleda" as UC_Pregled
}

Roditelj --> UC_MojaDeca
Roditelj --> UC_Podnesi

Admin --> UC_Odobri
Admin --> UC_Odbij
Admin --> UC_Grupa
Admin --> UC_Evidencija
Admin --> UC_PregledPrisustva

UC_Odobri ..> UC_Knjizica : <<include>>
UC_Odobri ..> UC_Pregled : <<include>>
ZdrSrv --> UC_Knjizica
ZdrSrv --> UC_Pregled

@enduml
